create_button = '.action.submit'
input_first_name = '#firstname'
input_last_name = '#lastname'
input_email = '#email_address'
input_password = '#password'
input_confirm_password = '#password-confirmation'
success_message = '.message-success'

error_first_name = '#firstname-error'
error_last_name = '#lastname-error'
error_email = '#email_address-error'
error_password = '#password-error'
error_confirm_password = '#password-confirmation-error'
error_message_registration = '.page.messages'
